# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93762d59744a3c19336a767b11ebe3447e1802c9bd08214fd18c62284938c585ad081f66d5cad981d5009f0e4b3ca81424817a5b0d64b4f4eccc6bdefad056d8

test:
  secret_key_base: 51e11c1b63b72ca64e63328d128e79a3abf4d2b9adcf761edc725e492ed382c943e47d78f82e5ccc616672445f63d913106736bae12e2fa457abab0f07be0483

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
